### PR TITLE
Add a volumetric fog demo

### PR DESCRIPTION
**Pull request by Calinou**
**Marked as draft** as I need help to get the mouselook script working again. It's based on https://github.com/godotengine/godot-demo-projects/blob/master/3d/waypoints/camera.gd, but with the 4.0 changes, I couldn't figure out how to make it work as expected.

This is an example of Godot's volumetric fog capabilities with the Vulkan renderer.

Showcased features are:

- Positive/negative density volumes that affect albedo (incoming light) and emission.
- Box/ellipsoid shapes, height falloff, and density modulation using a 3D texture.
- Temporal reprojection for greater stability and avoiding flickering.
  - The difference is demonstrated with a moving fog volume.
- Global density adjustment. With FogVolume nodes that have a positive density, it's possible to apply volumetric fog only in specific areas.

## TODO

- [ ] Add custom fog shader example (some 3D noise is likely a good start).

## Preview

Volumetric Fog

## Video

https://user-images.githubusercontent.com/180032/139598188-8284d6d7-cade-491b-b754-8519f8fc2ae2.mp4

### CODE REVIEW

**Comment by ScorpionInc** [comment]
I got the camera script to run on 4.0 alpha 1 with minor tweaks. Also got it to be able to go up and down as well. Available here: https://github.com/ScorpionInc/CameraLook-Test-Godot-4.0-Alpha1 hope it helps looking forward to trying out this demo.

**Comment by ScorpionInc** [comment]
Just tested the demo the camera script seems fine to me the only change I had to do was from: `transform.basis = Basis(rot, 0)` to: `transform.basis = Basis(Quaternion(rot))` hope this helps o/ I was tying to help with the shader but I'm still learning, I'll let you know if I get anything decent working.

**Comment by aaronfranke** [comment]
@ScorpionInc In Godot 4.0, instead of a constructing using Euler angles, you use the new explicit Basis `from_euler` method.

**Review by aaronfranke — APPROVED** [review]

**Comment by aaronfranke** [comment]
Thanks!

**Pull request merged**
