### PR TITLE
Fix window management demo for 4.0

### PR DESCRIPTION
**Pull request by voylin**
Fixing the problem which @aaronfranke mentioned in PR #737
Some functions are not present inside of Godot 4.0 so for the time being I commented them out as this demo will probably need more changes by the end of the alpha.

### CODE REVIEW

**Comment by aaronfranke** [comment]
The text in Godot 4 seems to be a lot larger by default, especially the size of the newline. The text on the right isn't rendering quite right, for example the value of "Size" is overlapping the "Mode". We should consider replacing the `\n` and have this info be inline at least for the properties with short names ("Screen0 Resolution:" probably stlll deserves two lines).

I think this is a Godot bug, but I'm getting this error from line 47 of `control.gd`:

```
E 0:00:01:0122   _physics_process: Condition "!windows.has(p_window)" is true. Returning: Size2i()
  <C++ Source>   platform/linuxbsd/display_server_x11.cpp:1719 @ window_get_size()
  <Stack Trace>  control.gd:47 @ _physics_process()
```

**Comment by voylin** [comment]
> The text in Godot 4 seems to be a lot larger by default, especially the size of the newline. The text on the right isn't rendering quite right, for example the value of "Size" is overlapping the "Mode". We should consider replacing the `\n` and have this info be inline at least for the properties with short names ("Screen0 Resolution:" probably stlll deserves two lines).
> 
> I think this is a Godot bug, but I'm getting this error from line 47 of `control.gd`:
> 
> ```
> E 0:00:01:0122   _physics_process: Condition "!windows.has(p_window)" is true. Returning: Size2i()
>   <C++ Source>   platform/linuxbsd/display_server_x11.cpp:1719 @ window_get_size()
>   <Stack Trace>  control.gd:47 @ _physics_process()
> ```

I'm not seeing that error. But I fixed the UI issues by removig some of the '\n' and also by using VBoxContainers.

**Comment by aaronfranke** [comment]
The buttons seem too close to the edge, and we can improve the anchor points to make the UI layout cleaner:

Screenshot from 2022-05-07 21-19-57
Screenshot from 2022-05-07 21-18-33

**Comment by voylin** [comment]
> The buttons seem too close to the edge, and we can improve the anchor points to make the UI layout cleaner:

Really looks better like that indeed, added the padding.

**Review by aaronfranke — COMMENTED** [review]
Looks good, but please update the commit message to something more descriptive than "Fix".

**Comment by voylin** [comment]
> Looks good, but please update the commit message to something more descriptive than "Fix".

'Fix' is fixed. ;)

**Review by aaronfranke — APPROVED** [review]

**Pull request merged**
