### PR TITLE
Rewrite the 2d/navigation demo so it's easier to understand

### PR DESCRIPTION
**Pull request by NathanLovato**
The original code could be made much simpler. I also added some comments for learning purposes.

### CODE REVIEW

**Comment by akien-mga** [comment]
It's fine that you renamed the `agent.png` and `path.png` files, but you should remove the old ones (with `git rm` - or alternatively you could have renamed them with `git mv` -- but no need to redo it, manual rename + `git rm` is equivalent for git).

**Comment by akien-mga** [comment]
There's also `navigation.tscn` that should be removed. And of course the `.import` files for the two renamed textures.

**Comment by NathanLovato** [comment]
My bad, forgot to do that. Should be fixed

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
