### PR TITLE
Update Space Shooter demo to 2.1.5

### PR DESCRIPTION
**Pull request by PetePete1984**
**What's the point of this, why 2.1.5?**
- To serve as a mostly complete game demo using current methods and workflows, as well as a base for a future 3.1 rewrite that dives into new features and shows the differences / pitfalls when upgrading a project

Major changes from the previous iteration:
- added Readme
- included sensible directory structure
- resizable window now uses stretching
- main menu UI organized in containers
- less reliance on get_parent() or get_node("..") calls
- more usage of signals and groups
- split the large level scene into enemies & tilemap scenes
- moved the hud out of the player scene and into the main game scene
- player can now shoot by holding the space bar

Room for improvement:
- the enemies use very similar code and could be generalized more

### CODE REVIEW

**Comment by rhulha** [comment]
Space Shooter ? Yes Please !

**Comment by aaronfranke** [comment]
@PetePete1984 What's the status of this? I don't think it makes sense to extensively modify the 2.1 branch. If you want to rewrite it for Godot 3.1, that is released now.

**Comment by PetePete1984** [comment]
@aaronfranke this 2.1.5 branch is finished, but I never got around to building a 3.1 version. The rewrite was mostly done because this demo was one of the most complete ones in the repo, but it also used some questionable (imo) approaches.

**Comment by aaronfranke** [comment]
So, this PR is not perfect, it does a few weird things like creating an "assets" folder with only one item in it, generally over-organizing, and some files don't end with newlines. Also, I don't use Godot 2.1, so I might not be the best person to review this. That being said: 

* It's overall an improvement from what I can tell, with no obvious regressions.

* I don't want to tell you to make changes to this PR, since it's for such an old version of Godot, I don't want to waste your time working on something that possibly nobody would ever use.

* I don't want this PR to remain in limbo forever, and nobody else is reviewing it.

So, I'll just go ahead and merge this, and let's just close this box forever afterwards.

**Pull request merged**
