### PR TITLE
Rigid character 3d platformer demo

### PR DESCRIPTION
**Pull request by kubecz3k**
Player code is ported from previous demos (2.1)

### CODE REVIEW

**Comment by akien-mga** [comment]
Sorry for the delay. Is it still up to date with current physics in the master branch?

**Comment by kubecz3k** [comment]
@akien-mga I guess it wont work because of api breakage (like fixed_process rename or others probably). Not sure how much sense its now to merge. Seen reduz had new models for platformer demo + it wont work after bullet merge. When reduz will update current demo with new assets, and we will have new physics I will do new pr.

**Comment by akien-mga** [comment]
Ok, let's close this one for now then? Or do you prefer to keep it open as a reminder? I don't mind either way.

**Comment by kubecz3k** [comment]
Yes I think we can close

**Pull request closed without merging**
