### PR TITLE
Add joints test to 2D/3D physics tests

### PR DESCRIPTION
**Pull request by pouleyKetchoupp**
Functional test used for checking/debugging all different joint types.

Also added the possibility to pick and move 2D and 3D bodies to some tests.

### CODE REVIEW

**Comment by aaronfranke** [comment]
For both 2D and 3D, "Functional Tests" -> "Joints" -> "TEST OPTIONS" -> "Test case" -> "Destroy attached body", if you toggle this on and then toggle it off, it crashes.

For both 2D and 3D, "Functional Tests" -> "Joints" -> "TEST OPTIONS" -> "Joint Type", the joints are switchable with numbers, except that the number 1 isn't working for selecting Pin Joint.

For 3D, if "Functional Tests" -> "Joints" is loaded, then moving the top box doesn't affect the bottom one. But if "TEST OPTIONS" -> "Joint Type" -> "Pin Joint (1)" is selected, it starts working.

**Comment by pouleyKetchoupp** [comment]
Thanks for catching all of these!

> For both 2D and 3D, "Functional Tests" -> "Joints" -> "TEST OPTIONS" -> "Test case" -> "Destroy attached body", if you toggle this on and then toggle it off, it crashes.

Fixed

> For both 2D and 3D, "Functional Tests" -> "Joints" -> "TEST OPTIONS" -> "Joint Type", the joints are switchable with numbers, except that the number 1 isn't working for selecting Pin Joint.

Fixed

> For 3D, if "Functional Tests" -> "Joints" is loaded, then moving the top box doesn't affect the bottom one even though it says Pin Joint. But if "TEST OPTIONS" -> "Joint Type" -> "Pin Joint (1)" is selected, it starts working.

This is an issue with Bullet. It seems it's related to the child body being asleep (it happens if you wait for ~3s after the joint is setup) and doesn't occur when Godot Physics is on. I'll enter an issue.

**Comment by aaronfranke** [comment]
> > For both 2D and 3D, "Functional Tests" -> "Joints" -> "TEST OPTIONS" -> "Test case" -> "Destroy attached body", if you toggle this on and then toggle it off, it crashes.
> 
> Fixed

Now if I toggle it, I get:

```
E 0:00:16.750   get: Condition "!id_map.has(p_rid.get_data())" is true. Returned: __null
  <C++ Source>  ./core/rid.h:150 @ get()
  <Stack Trace> test_joints.gd:99 @ _create_joint()
                test_joints.gd:53 @ _process()
E 0:00:16.750   body_remove_collision_exception: Condition "!body" is true.
  <C++ Source>  servers/physics_2d/physics_2d_server_sw.cpp:966 @ body_remove_collision_exception()
  <Stack Trace> test_joints.gd:99 @ _create_joint()
                test_joints.gd:53 @ _process()
```

And if I toggle it twice, it crashes.

**Comment by pouleyKetchoupp** [comment]
These crashes are related to https://github.com/godotengine/godot/issues/44510 (they are the reason why I have this test case).

They will be fixed with https://github.com/godotengine/godot/pull/44703 (4.0) and https://github.com/godotengine/godot/pull/44704 (3.2).

**Review by aaronfranke — CHANGES_REQUESTED** [review]
Unnecessary parenthesis

**Comment by pouleyKetchoupp** [comment]
> 
> 
> Unnecessary parenthesis

All removed, along with some other ones I found in the project.

**Comment by aaronfranke** [comment]
In 3D, for hinge joint:

```
W 0:00:08.141   set_param: The HingeJoint parameter 0 is deprecated.
  <C++ Error>   This method has been deprecated and will be removed in the future.
  <C++ Source>  modules/bullet/hinge_joint_bullet.cpp:120 @ set_param()
  <Stack Trace> test_joints.gd:132 @ _create_joint()
                test_joints.gd:52 @ _process()
```

In 3D, for generic 6DOF joint:

```
E 0:00:10.977   get: Condition "!p_rid.is_valid()" is true. Returned: __null
  <C++ Source>  ./core/rid.h:149 @ get()
  <Stack Trace> test_joints.gd:126 @ _create_joint()
                test_joints.gd:52 @ _process()
E 0:00:10.977   generic_6dof_joint_set_precision: Condition "!joint" is true.
  <C++ Source>  modules/bullet/bullet_physics_server.cpp:1476 @ generic_6dof_joint_set_precision()
  <Stack Trace> test_joints.gd:126 @ _create_joint()
                test_joints.gd:52 @ _process()
```

If these are also expected like the ones above, then this can be merged.

**Comment by pouleyKetchoupp** [comment]
Yes, I can confirm these are known issues as well.

**Review by aaronfranke — APPROVED** [review]

**Pull request merged**
