### PR TITLE
More projects converted to and tested with Godot 3.1

### PR DESCRIPTION
**Pull request by t-karcher**

### CODE REVIEW

**Comment by StraToN** [comment]
Supersedes #325

**Comment by t-karcher** [comment]
Closes #307

**Comment by aaronfranke** [comment]
@akien-mga https://github.com/godotengine/godot-demo-projects/issues/307

**Comment by akien-mga** [comment]
Thanks for the reminder, I'll review asap.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
