### PR TITLE
Add a 3D procedural materials demo

### PR DESCRIPTION
**Pull request by Calinou**
This demo includes procedurally generated materials with 3 different techniques:

- **[NoiseTexture2D](https://docs.godotengine.org/en/stable/classes/class_noisetexture2d.html):** Built-in class that generates images on the CPU based on noise patterns (such as Simplex or Cellular). This is suited for static textures only. Texture generation is done asynchronously and is faster than using scripting, since the noise algorithms are implemented in C++ in the engine.

- **Scripting:** Uses the [Image](https://docs.godotengine.org/en/stable/classes/class_image.html) class to procedurally generate an [ImageTexture](https://docs.godotengine.org/en/stable/classes/class_imagetexture.html) on the CPU. This is suited for static textures only. This approach is more flexible than NoiseTexture2D, but is slower to generate textures. Once the texture is generated, rendering performance is identical to NoiseTexture2D.

- **Shaders:** Uses a 2D shader on a [ColorRect](https://docs.godotengine.org/en/stable/classes/class_colorrect.html) node that matches a [Viewport](https://docs.godotengine.org/en/stable/classes/class_viewport.html)'s size with the resulting [ViewportTexture](https://docs.godotengine.org/en/stable/classes/class_viewporttexture.html) applied to a material. This is updated on the GPU in real-time, and is most suited for animated textures. This approach can also be used for static textures, with a lower performance overhead since the texture doesn't need to be updated every frame.

## Preview

procedural_materials webp

### CODE REVIEW

**Comment by mhilbrunner** [comment]
Really cool demo! On Windows 10, it hangs a bit for me on load when starting the run in editor. It also outputs this:
```
ERROR: Viewport Texture must be set to use it.
   at: (scene/main/viewport.cpp:116)
ERROR: Viewport Texture must be set to use it.
   at: (scene/main/viewport.cpp:111)
ERROR: Node not found: "Testers/ShaderPlasma/SubViewport" (relative to "WorldEnvironment").
   at: (scene/main/node.cpp:1364)
ERROR: ViewportTexture: Path to node is invalid.
   at: (scene/main/viewport.cpp:76)
ERROR: Viewport Texture must be set to use it.
   at: (scene/main/viewport.cpp:116)
ERROR: Viewport Texture must be set to use it.
   at: (scene/main/viewport.cpp:111)
```

Then it works correctly. On exit, it spams a bit more errors, not sure these are important though?

<details>
  <summary>Console output</summary>

```
ERROR: Condition "!material" is true. Returning: true
   at: material_casts_shadows (servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2824)
ERROR: Condition "!material" is true. Returning: false
   at: material_is_animated (servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2811)
ERROR: Condition "!material" is true.
   at: material_get_instance_shader_parameters (servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2837)
ERROR: Condition "!material" is true.
   at: material_update_dependency (servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2849)
ERROR: Condition "!material" is true. Returning: true
   at: material_casts_shadows (servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2824)
ERROR: Condition "!material" is true. Returning: false
   at: material_is_animated (servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2811)
ERROR: Condition "!material" is true.
   at: material_get_instance_shader_parameters (servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2837)
ERROR: Condition "!material" is true.
   at: material_update_dependency (servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2849)
ERROR: Condition "!material" is true. Returning: true
   at: material_casts_shadows (servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2824)
ERROR: Condition "!material" is true. Returning: false
   at: material_is_animated (servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2811)
ERROR: Condition "!material" is true.
   at: material_get_instance_shader_parameters (servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2837)
ERROR: Condition "!material" is true.
   at: material_update_dependency (servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2849)
ERROR: Condition "!material" is true. Returning: true
   at: material_casts_shadows (servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2824)
ERROR: Condition "!material" is true. Returning: false
   at: material_is_animated (servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2811)
ERROR: Condition "!material" is true.
   at: material_get_instance_shader_parameters (servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2837)
ERROR: Condition "!material" is true.
   at: material_update_dependency (servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2849)
ERROR: Condition "!material" is true. Returning: true
   at: material_casts_shadows (servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2824)
ERROR: Condition "!material" is true. Returning: false
   at: material_is_animated (servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2811)
ERROR: Condition "!material" is true.
   at: material_get_instance_shader_parameters (servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2837)
ERROR: Condition "!material" is true.
   at: material_update_dependency (servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2849)
ERROR: Condition "!material" is true. Returning: true
   at: material_casts_shadows (servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2824)
ERROR: Condition "!material" is true. Returning: false
   at: material_is_animated (servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2811)
ERROR: Condition "!material" is true.
   at: material_get_instance_shader_parameters (servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2837)
ERROR: Condition "!material" is true.
   at: material_update_dependency (servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2849)
ERROR: Condition "!material" is true. Returning: true
   at: material_casts_shadows (servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2824)
ERROR: Condition "!material" is true. Returning: false
   at: material_is_animated (servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2811)
ERROR: Condition "!material" is true.
   at: material_get_instance_shader_parameters (servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2837)
ERROR: Condition "!material" is true.
   at: material_update_dependency (servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2849)
ERROR: Condition "!material" is true. Returning: true
   at: material_casts_shadows (servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2824)
ERROR: Condition "!material" is true. Returning: false
   at: material_is_animated (servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2811)
ERROR: Condition "!material" is true.
   at: material_get_instance_shader_parameters (servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2837)
ERROR: Condition "!material" is true.
   at: material_update_dependency (servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2849)
ERROR: Condition "!material" is true. Returning: true
   at: material_casts_shadows (servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2824)
ERROR: Condition "!material" is true. Returning: false
   at: material_is_animated (servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2811)
ERROR: Condition "!material" is true.
   at: material_get_instance_shader_parameters (servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2837)
ERROR: Condition "!material" is true.
   at: material_update_dependency (servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2849)
ERROR: Condition "!material" is true. Returning: true
   at: material_casts_shadows (servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2824)
ERROR: Condition "!material" is true. Returning: false
   at: material_is_animated (servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2811)
ERROR: Condition "!material" is true.
   at: material_get_instance_shader_parameters (servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2837)
ERROR: Condition "!material" is true.
   at: material_update_dependency (servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2849)
```
</details>

**Comment by Calinou** [comment]
There should be a loading screen appearing on Linux at least, not sure why it doesn't appear on Windows. Can you try changing `loading.gd` to make it appear for a few more frames?

**Comment by InfiniteProductions** [comment]
I have some warnings:

> [Ignore]Line 15 (INTEGER_DIVISION):Integer division, decimal part will be discarded.
> [Ignore] Line 20 (INTEGER_DIVISION):Integer division, decimal part will be discarded.
> [Ignore]Line 20 (INTEGER_DIVISION):Integer division, decimal part will be discarded.
> [Ignore]Line 22 (INTEGER_DIVISION):Integer division, decimal part will be discarded.
> [Ignore]Line 22 (INTEGER_DIVISION):Integer division, decimal part will be discarded.

and errors too:
> E 0:00:06:0563   loading.gd:13 @ _ready(): Viewport Texture must be set to use it.
>  <C++ Source>   scene/main/viewport.cpp:116 @ get_height()
>  <Stack Trace>  loading.gd:13 @ _ready()

>E 0:00:06:0565   loading.gd:13 @ _ready(): Viewport Texture must be set to use it.
>  <C++ Source>   scene/main/viewport.cpp:106 @ get_width()
>  <Stack Trace>  loading.gd:13 @ _ready()

and pretty much the same flow of "errors" on exit in console.

I have the loading screen displayed for a few seconds (~ 5-10s).

Godot v4.1.dev2.official [668cf3c66], Windows 7 64b, GeForce 780M GTX

**Comment by Calinou** [comment]
> and errors too:

You can ignore those errors; they're a well-known engine issue.

**Comment by jtnicholl** [comment]
pixel_art.tres is 2.37 MB, looks like there's an image embedded in it.

**Comment by Calinou** [comment]
> pixel_art.tres is 2.37 MB, looks like there's an image embedded in it.

Good catch, fixed :slightly_smiling_face: 

This should allow the scene to load a bit faster.

**Comment by jtnicholl** [comment]
> Good catch, fixed slightly_smiling_face

It's only down to 1.21 MB now, the normal texture is still there.

**Comment by Calinou** [comment]
> It's only down to 1.21 MB now, the normal texture is still there.

Fixed.

**Review by moth-boi — APPROVED** [review]
I've gone through the code and given it a solid try to make sure everything's working correctly. 👍

**Pull request merged**
