### PR TITLE
Add JRPGish demo

### PR DESCRIPTION
**Pull request by henriiquecampos**
Well, as suggested in #263 I'm making the PR for a small JRPG demo currently it works as follow:

- The game has 2 states: **Exploration** and **Combat** which are two screens that are removed/added to the SceneTree depending on which state the game is currently
- Exploration is a basic topdown grid movement system, character can walk, bump on obstacles and if it bumps on an opponent, a dialog will show up, when dialog finishes the combat is built.
- **Actor** (you will see this a lot in the demo) is an agent of a system.
- The Actors for the exploration also carry a **Combat Actor** `PackedScene` variable which is exposed in the inspector, so to build a combat you can design a new enemy, drag and drop into the Exploration `Actor.combat_actor` slot in the inspector and you are done
- As for the Combat, it just takes an array of **Combat Actors** to build the combat it is currently not very scalable, since the interface has space for just 2 **Actors**, but nothing actually prevents from having more, it will only seem very ugly
- The combat is take on turns with targets being fixed and automated
- When someone dies a signal is emitted, the Combat finishes, going back to Exploration and a Dialog is shown depending on who won the combat.

Most of the systems were made with mentoring of @NathanLovato but since I ducktaped them together by myself, it will probably be a mess and will need some hard reviewing, so don't take easy on pointing bad practices.

That said, thanks a lot for the opportunity, hope this helps some peeps :blue_heart:

### CODE REVIEW

**Comment by aztecsensei** [comment]
this is great! godot need more game demos.
base on your experience,how much difficult would it be to make a demo that plays like Final fantasy 7?
im talking about the programming side. of course. :)

**Comment by NathanLovato** [comment]
I'll review it after I pushed/scheduled the next Godot course update and batch of tuts.

**Comment by NathanLovato** [comment]
Some general issues to fix:
- missing last lines on some script files
- when you talk to the opponent multiple times, you try to connect the signals again and get an error

image

- Deffend -> defend (and it feels this button + method should be `heal` or something?)

image

**Comment by Zeph-dev** [comment]
Could be a link to the items, or where healing, catching items are stored perhaps? Or do you already have a button for that?

**Comment by henriiquecampos** [comment]
Hey there finally was able to update this :stuck_out_tongue: 

> and it feels this button + method should be heal or something?)

As I'm using [Health.gd](https://github.com/godotengine/godot-demo-projects/pull/267/files#diff-288b61e17803ca41107d4b6c67c188d8R8) to calc the amount of damage the character takes, when using **Defend** it increases the `Health.armor`, decreasing the total damage, no healing there. :stuck_out_tongue_closed_eyes:

**Comment by NathanLovato** [comment]
Okay there's some typos, and the inventory button does nothing. Aside from that it works well. Let me merge and fix that

**Pull request merged**
