### PR TITLE
BoxContainer Class Nodes Demo

### PR DESCRIPTION
**Pull request by Mr-K-GameDev**
### Brief background on it:

At first, I wanted to make a demo, about the **whole Container Class nodes**.... but i looked at it,
and realized that **The Class** is Too Big, i even tried making a Good not complicated Demo, but failed at doing so,
So i took the BoxContainer Class nodes, as a Class to take on.

I've tried my best, sticking with the **GDscript style guide**, but at the same time make the code look good,
and explaining what parts do on the way.

## Functionalities:
- you can **select** a ColorRect by *L.clicking* on it, and **change it's color** (through the Color Picker).
- By holding down the Ctrl key, you can **select multiple ColorRects**,
and all of them will change there color (*again* Though the Color Picker).

## ScreenShot

screen_shot1

### CODE REVIEW

**Comment by Mr-K-GameDev** [comment]
Hay, i'm kinda new to contributing to this repo, just woundering why did the file_format check faild?
like... i followed the GDscript style guide, from start to finish, but it faild at an if statment (or a for idk).

**Comment by bruvzg** [comment]
> Hay, i'm kinda new to contributing to this repo, just woundering why did the file_format check faild?

You can click on "Details" and see diff from the `file_format`:

```diff
diff --git a/gui/box_container/box_container.gd b/gui/box_container/box_container.gd
index 934673b..3e52288 100644
--- a/gui/box_container/box_container.gd
+++ b/gui/box_container/box_container.gd
@@ -36,7 +36,7 @@ func _input(event):
 			selecting_multiple = true
 		elif event.is_action_released("ctrl"):
 			selecting_multiple = false
-		
+
 		# clears the items_selected array, if these three arguments are all true.
 		elif is_mouse_on_background and event.is_action_pressed("ui_select") and not selecting_multiple:
 			for i in range(items_selected.size()):
@@ -51,7 +51,7 @@ func select_item(color_rect):
 		items_selected.append(color_rect)
 		# Sets the child of last ColorRect visibility to true
 		items_selected[items_selected.size() - 1].get_child(0).set_visible(true)
-	
+
 	# if ctrl key is not held down, it will remove everything
 	# except the last rect you clicked.
 	if items_selected.size() > 1 and not selecting_multiple:
```

**Comment by bruvzg** [comment]
Also try using `optipng` or similar optimizer on the screenshot, it can be compressed from 186 to 53 KB.

**Comment by Mr-K-GameDev** [comment]
ohh thanks @bruvzg , gonna fix the style errors and do a git commit --amend.

**Comment by Mr-K-GameDev** [comment]
.... i'm still very confussed, i went a head and compared them.... no sign of any wrong style, and nothing wrong with the code it self.... idk what's wrong with, it just escapes after this if statment ( if items_selected.size() > 1 and not selecting_multiple: )

**Comment by Mr-K-GameDev** [comment]
after that is a for loop, and all of the pravite functions (every func name starts with _).... idk how to fix it

**Comment by Mr-K-GameDev** [comment]
ohh hahahhh, stupid me, the file_format log Tells ma what i should change, to fit the code formatting rules,
lol my bad guys, first time contributting to a repo like... ever.

**Comment by aaronfranke** [comment]
We already have a demo quite similar to this one, the Drag and Drop demo. We should just improve that one so that it uses containers and maybe allows multiple selection.

**Comment by Mr-K-GameDev** [comment]
Well..... all of my work has went away for nothing xd
ohh well, at least i learnt queit a bit from doing it, ok then gonna go ahead and try another idea.

**Pull request closed without merging**
