### PR TITLE
[WebSocket] Fix chat demo to updated TLS function.

### PR DESCRIPTION
**Pull request by Faless**
Old cert + key/servername have been replaced with the new TLSOption configuration object.

The scene changes are just the result of opening the project and re-saving the scene with godot 4.0.2 stable.

### CODE REVIEW

**Comment by Faless** [comment]
Needs cherry pick to the 4.0 brannch.

**Comment by Faless** [comment]
Let me know if you prefer I split the scene and GDScript changes.

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
Note that here is already https://github.com/godotengine/godot-demo-projects/pull/909

**Review by Calinou — APPROVED** [review]
Thanks!

**Pull request merged**
