### PR TITLE
Optimize all images using `oxipng -o6 --strip all --zopfli`

### PR DESCRIPTION
**Pull request by Calinou**
This will make tarballs smaller (which includes downloads from the Asset Library), at the cost of making the Git history larger by ~20 MB.

### CODE REVIEW

**Comment by aaronfranke** [comment]
Assuming this is a desired change, it needs to be rebased / redone first.

**Comment by akien-mga** [comment]
Needs to be rebased again, otherwise fine to merge.

**Comment by aaronfranke** [comment]
@akien-mga

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
