### PR TITLE
Improve 3D global illumination demo (4.0)

### PR DESCRIPTION
**Pull request by Calinou**
Follow-up to https://github.com/godotengine/godot-demo-projects/pull/718.

- Readd LightmapGI example.
- Allow toggling between the Once and Always update modes for the ReflectionProbe.
- Add a Decal node to act as a blob shadow for dynamic objects.
- Halve SSAO intensity for a better apperance in the demo's flat, bright surfaces.
- Halve ambient light sky contribution when using the disabled or lightmap-based GI modes. This prevents the level's shaded areas from looking too bright and blue (with lightmaps, this change only affects dynamic objects.)
- Enable FXAA and debanding for a better appearance.

### CODE REVIEW

**Review by adamscott — APPROVED** [review]
Good job. Seems fine to me.

**Comment by adamscott** [comment]
I don't think the it's the demo's fault, but it kept happening on some GI modes.

[Capture vidéo du 2022-11-24 20:34:31.webm](https://user-images.githubusercontent.com/270928/203883178-b6f1bc59-a932-43a9-b5cd-f43767a8525a.webm)

**Comment by Calinou** [comment]
Rebased and tested again on 4.0.beta13, it works as expected.

I also made an additional cosmetic change:

> - Halve ambient light sky contribution when using the disabled or lightmap-based GI modes. This prevents the level's shaded areas from looking too bright and blue (with lightmaps, this change only affects dynamic objects.)

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
