### PR TITLE
Update translation demo project to include changes from GSoC 2020 i18n

### PR DESCRIPTION
**Pull request by SkyLucilfer**
## NOTE: This is for Godot 4.0

As part of my GSoC work on i18n, I have updated the translation demo project to incorporate the newly implemented features (CSV plurals, PO plurals, POT generation etc.)

I'm making a pull request first for mentors to review. They should have other plans.

### CODE REVIEW

**Comment by aaronfranke** [comment]
@SkyLucilfer Soon we will begin porting the demos to the current master branch in preparation for Godot 4 alpha. Can you update this PR so that it works with the current master branch of Godot, and check if there is anything that needs doing before merging?

**Comment by aaronfranke** [comment]
@SkyLucilfer Can you rebase this PR and ensure it works with the latest master branch of Godot?

**Comment by Anutrix** [comment]
@SkyLucilfer Can you please rebase this PR?

**Comment by aaronfranke** [comment]
Closing as abandoned.

**Pull request closed without merging**
