### PR TITLE
Add a 3D labels and texts demo

### PR DESCRIPTION
**Pull request by Calinou**
This adds a demo showcasing [Label3D](https://github.com/godotengine/godot/pull/60386) and [TextMesh](https://github.com/godotengine/godot/pull/60507).

@bruvzg Is it OK to license `textmesh_texture.png` as CC0? Just making sure :slightly_smiling_face:

## Preview

3D Labels and Texts

### CODE REVIEW

**Comment by bruvzg** [comment]
> Is it OK to license textmesh_texture.png as CC0? Just making sure 🙂

Sure. It's 4 random gradients, there's nothing to license.

**Comment by adamscott** [comment]
I don't think this is normal.

Capture d’écran du 2022-11-24 20-23-46

**Comment by Calinou** [comment]
> I don't think this is normal.

Fixed :slightly_smiling_face:

**Comment by Calinou** [comment]
Rebased and tested again on 4.0.beta11, it works as expected.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
