### PR TITLE
'Navigation Polygon 2D' ported to Godot 4.1.1

### PR DESCRIPTION
**Pull request by Alex2782**
I have combined the script from the documentation with the old solution (click event with red dot)
https://docs.godotengine.org/en/latest/tutorials/navigation/navigation_introduction_2d.html#setup-for-2d-scene

https://github.com/godotengine/godot-demo-projects/assets/41921395/a21e9ab1-43e1-4c0b-820a-563a8ee23264

'NavigationPolygon' drawn again, it looked buggy.
image

### CODE REVIEW

**Comment by Alex2782** [comment]
how to fix these errors?

image

**Comment by Calinou** [comment]
You have trailing whitespace (tabs) in your code. I recommend enabling the **Trim Trailing Whitespace on Save** editor setting to get rid of them automatically :slightly_smiling_face:

**Comment by smix8** [comment]
If we rework and update the demo maybe we should save the NavigationPolygon resource to an external file as a binary .res file?

Right now it is stored embedded as plain text inside the navigation.tscn file, something that we should not teach to new users as it will bloat their scene files and make them super slow to load/save/update on large and complex navigation meshes.

**Comment by smix8** [comment]
>  don't know yet how to convert tres to res afterwards

Click the "Make Unique" again and "Save As" then you can save it as a new .res binary file.

**Comment by Alex2782** [comment]
@smix8 
The function `set_movement_target` was already in the character-GDscript, but unused (copied from the doc)
I moved the character to its own scene and deleted navigation.gd.

**now only one script** [character.gd](https://github.com/godotengine/godot-demo-projects/pull/955/files#diff-7280bfb9bd2ef09ebad7f3061d95505d1ee7f58db571cca2ed5cee721ce9ec1a)

`navigation_agent.debug_enabled = true` 👍 

https://github.com/godotengine/godot-demo-projects/assets/41921395/37e8388b-d4f5-4f6a-91c1-dbdd5b06d3fb

**Review by smix8 — APPROVED** [review]

**Review by Calinou — APPROVED** [review]
Tested locally on Godot 4.1.2, it works as expected.

Thanks!

**Pull request merged**
