### PR TITLE
Add 2.5D Demo Projects

### PR DESCRIPTION
**Pull request by aaronfranke**
A few users [have asked](https://github.com/godotengine/godot/issues/25980) how to create 2.5D games in Godot, so I've created two demo projects that demonstrate how such a thing would be implemented. Actually, they are both the same project, the difference is that one is written entirely in GDScript and one is written mostly in C#.

Though currently in a functional state, this is a work-in-progress. A few things on the to-do list:

- [x] ~~The platform texture used in the demo is just the first result I found on Google images. It needs to be replaced. I'm not an artist, so contributions welcome.~~ It has been replaced!

- [x] ~~The demo character could also use some improvements. Right now it's just the Godot logo.~~ Thanks to @Steph155's excellent work we have a character now!

- [x] ~~There is currently no project icon, which would be nice to have.~~ Icon is now character's face.

- [ ] The code should be reviewed by people.

ZIP download link: https://github.com/aaronfranke/godot-demo-projects/archive/2point5d.zip

### CODE REVIEW

**Comment by Steph155** [comment]
@aaronfranke 
I'm a student in software engineering but with not so terrible programming experience(still < one year in any programming language)... But I'm an artist too. You say you need a platform texture for the demo project. Thank God I have a graphic tablet and also do pixel art... Well I needed it to build my own video game which is still being developed. Here's an example of my latest works :
kuga64_standing_xxl

So if you need a texture, you can ask me, specify the texture resolution ideal for you. And if instead you want a tileset, I'm ready to help. Just reply by tagging my name...

**Comment by YeldhamDev** [comment]
Did a superficial look, interesting way of doing it. For now, my only complain is that is very hard to tell height difference between platforms, if there was a way for them to cast a shadow below them, maybe with some shader wizardry.

**Comment by Steph155** [comment]
@YeldhamDev
It'd be quite interesting to that. And I understand it's possible to set shader on 2D textures using normal maps... But it's optional. Besides, if @aaronfranke  had used a good tileset, there wouldn't be this problem I bet. But he is not an artist. Sire @aaronfranke, I can just find/make a quick asset if you need. 
For a start, you can check this website(https:\\opengameart.com).

**Comment by aaronfranke** [comment]
@YeldhamDev Yes, of course. We could work on shadows, perhaps making a large floor below all of the platforms where the shadows would show up. I'm not sure what would be the best way to have "partial" shadows though, platforms partially overlapping each other would have floating shadows right now... @Steph155 mentioned normal maps, I am not an expert on 2D so I'm not sure how that could be made to work procedurally based on the surrounding objects (or, it could just be hard-coded...)

@Steph155 Pretty much any resolution is fine, but I would suggest it being lower resolution than it currently is (logo is 64x64) because I currently have the camera set to zoom 2 to make it easier to see everything. You can preview how the objects would look simply by replacing the textures, and give proper behavior simply by changing the 3D collision boxes and/or constants such as SCALE.

**Comment by Steph155** [comment]
@aaronfranke  Wow, check this ! 
It might be inspiring for the current project. The developer didn't really need a 3D node but just a hack with scripts including a **`draw()`** method.. 
https://www.youtube.com/watch?v=jRAXB-16_7s

Well, I also wanted to ask, where do I put the sprite sheets for the project's character ? Here ?

**Comment by aaronfranke** [comment]
Feel free to post here, or link me a branch on a fork. In either case I'll add you as a contributor.

The method used in this demo is quite flexible since it works with arbitrary colliders, not just AABBs defined in code in that video. With this demo, it's possible to make an irregularly shaped or diagonal platform, as well as slopes, since it uses full 3D math, though I haven't featured this in the demo.

**Comment by Steph155** [comment]
preview
@aaronfranke 
I really lacked free time lately. Here's a sprite preview of the character I propose for the project.
If it's good, then I start the animation process and finish the coloring for it to look more appealing.
So how is it ? Should I also make attack animations ? If yes, then I'll try doing something basic, both melee and shooting animations.
The original size is about max 64 x 64 pixels.

**Comment by aaronfranke** [comment]
@Steph155 I really like it! It looks like an awesome robot, and it's even purple to match with Node25D. I don't know what you are planning to change about it but it looks like you're going the right direction.

When it comes to animation, that's entirely up to you. Attack animations are not really necessary for this demo project, but they would be welcome if you wanted to make it.

Also, while we can probably get away with using the same perspective for 45 degree, isometric, and oblique Z, we would want a slightly modified one for front side, and a different one for top down. Actual 2.5D games don't need multiple perspectives, but this demo project should showcase them.

**Comment by Steph155** [comment]
Greetings.
Here's the idle spritesheet. Hope it's alright...
I'm making the run spritesheet as well.
I drop it here when done...
Robi_Idle_sheet

**Comment by Steph155** [comment]
@aaronfranke 
Here you go. The spritesheet for the run animation is done...
Robi_Run_SSheet

**Comment by Steph155** [comment]
@aaronfranke 
Greetings Aaron.
Here's the jump anim spritesheet. I used a two frames-based reference and since the robot is symmetrical, I saved my job to 10 sprites instead of 16. Level design comes next...
Robi_jump_sheet

**Comment by Steph155** [comment]
This is my first tilesheet ever...
It's not so terrible, but I believe there are quite enough types of textures, and combining them could help build complex levels. Alright.  Dropping it here...
Asset_2
Asset_2_a

**Comment by aaronfranke** [comment]
After a very long time of waiting, I'm marking this as ready for review. If nobody reviews it I'll probably still merge it, but I would love to get feedback on everything so far.

The current state of the project not only allows you to create 2.5D games, but also has a 2.5D editor viewport with a translation gizmo to make the process easy and seamless.

2.5D Editor Viewport

Before anyone reports issues with the Mono C# version: Yes I know it throws errors when the project is first opened and that Gizmo25D doesn't work properly for some reason, but I have no idea what is causing these issues. It's most likely just Godot bugs. Aside from that, it works great.

**Comment by golddotasksquestions** [comment]
How would one "review" it? Where can I find the download link?

**Comment by qarmin** [comment]
Here - https://github.com/aaronfranke/godot-demo-projects/archive/2point5d.zip

**Comment by golddotasksquestions** [comment]
Thanks @qarmin , is there some link somewhere I'm just to blind to see, or did you went and searched manually through aaronfranke github page?

**Comment by qarmin** [comment]
I just go to this PR branch, and then I downloaded it.  
It is really hard to find first time this.
1.
Zrzut ekranu z 2020-03-01 17-55-58
2.
Zrzut ekranu z 2020-03-01 17-56-43

**Comment by golddotasksquestions** [comment]
Finally found it in the "misc" folder.
Right after installing it, the first time I open the project I immediately get this popup warning:
"Unable to load addon script from path: 'res://addons/node25d/node25d_plugin.gd' There seems to be an error in the code, please check the syntax."

**Comment by Steph155** [comment]
Execute Godot as admin to fix that.

**Comment by aaronfranke** [comment]
@golddotasksquestions Close and re-open the project. That bug happens whenever Godot hasn't imported everything yet, I don't think there's anything I can do about it.

**Comment by golddotasksquestions** [comment]
The cube demo looks really impressive!
With the platformer demo the character sometimes jerks forward in it's position (with the camera) what seems like just a frame or two. I have not found out when exactly this jitter-jerk appears or why, but it's happening about 3 times a minute.

**Comment by aaronfranke** [comment]
@golddotasksquestions Does changing the physics engine help? I haven't really seen such issues on my system, any debugging you can do would be greatly appreciated.

**Comment by golddotasksquestions** [comment]
Sure, I can do some testing. What do you mean by "changing the physics engine"?

**Comment by aaronfranke** [comment]
Screenshot from 2020-03-01 15-19-43

**Comment by golddotasksquestions** [comment]
2D, 3D "Godot Physics" makes the shadow disappear and jitter, but mostly just disappear. Character seems fine.
2D "Default",  3D "Bullet" seems to work fine
2D "Godot Physics", 3D Bullet" seems to also work fine, though I have seen the character jerking forward once (not as much as in default settings)

**Comment by Calinou** [comment]
2D only supports the default Godot Physics, so 2D "Default" and "2D "Godot Physics" are effectively identical. We should tweak the property hints to reflect this.

**Pull request merged**
