### PR TITLE
Docs: 2D Platformer - Update Pause Mode Comments

### PR DESCRIPTION
**Pull request by HaywardMorihara**
I believe this comment got out-of-date (based on the fact that the `Stage` scene seems like something that was in an older version of the demo: https://github.com/godotengine/godot-demo-projects/blob/81441c42b79e38e54c2bc38acee3205f22431738/2d/platformer/Stage.tscn), so updated the comment to reflect the current state of the demo, along with some other information that I thought a developer might find helpful.

### CODE REVIEW

**Comment by HaywardMorihara** [comment]
I'm confused about the GH Action failure (I don't see a message about what's wrong with the format of the comment?)

 I'm assuming it's because of the `*` in the comment? https://github.com/godotengine/godot-demo-projects/runs/7271893814?check_suite_focus=true#step:4:16 

Tried replacing the stars with a numbered list

**Comment by Calinou** [comment]
> I'm confused about the GH Action failure (I don't see a message about what's wrong with the format of the comment?)

There appears to be trailing whitespace at the end of the life.

**Comment by HaywardMorihara** [comment]
🤦‍♂️ my mistake, removed the whitespace!

**Review by aaronfranke — APPROVED** [review]
Makes sense to me.

**Pull request merged**
