### PR TITLE
Pause Menu Demo

### PR DESCRIPTION
**Pull request by Mr-K-GameDev**
# Pause Menu Demo

Made a Demo show casing how to make a Pause Menu,

### Features

1. Pause the Scene Tree.
2. Making a Polished Pause Menu, using a Theme, and doing the animations with Tween Class.

**The polishing is a work in Progress**

### Screen Shots
screen_shot1

### CODE REVIEW

**Comment by aaronfranke** [comment]
The Platformer 2D demo already has a pause menu:

Screenshot from 2020-11-03 16-29-05

And we already have a minimal pausing demo (no menu):

Screenshot from 2020-11-03 16-29-51

So I don't see why we need this demo, we already have two projects that demonstrate how to pause.

I suggest that you chat with me before making these, perhaps you can jump on Discord or IRC.

**Comment by Mr-K-GameDev** [comment]
well..... great. made alot of changes to it......
.
.
.
crap, not again man

**Comment by Mr-K-GameDev** [comment]
ok @aaronfranke , is there a Discord server for this repo os something?
like.... i really wanna Contribute to this repo ( mainly The gui Demos), but i can't because every time i make a Demo,
There's a similer looking Demo.

**Comment by aaronfranke** [comment]
@Mr-K-GameDev See https://godotengine.org/community and https://discord.gg/4JBkykG

There isn't a Discord for the demos specifically, but I often hang around voice chat, and you can always ask in text channels.

**Pull request closed without merging**
