### PR TITLE
3D Inverse Kinematics Godot 4 Conversion (Partial)

### PR DESCRIPTION
**Pull request by chrisl8**
This is an initial attempt to convert the 3D Inverse Kinematics demo, related to updating all Demos to Godot 4 Issue #697

The project doesn't entirely work yet, but it runs. I am still working on making it work fully, but at least it starts now instead of crashing and you can cycle through the scenes and read all of the text.

I'll keep updating this when I make more parts work. I leave it up to you if you want to merge it now or wait until I have made it more functional.

I hit some of the files with my code formatter, if white-space updates are not wanted I can remove those.

### CODE REVIEW

**Comment by chrisl8** [comment]
As I wrestled with this, somebody told me that Skeleton3D is going away, because it doesn't work. Is that true? It would explain why I'm struggling with it so much.

**Comment by GeorgeS2019** [comment]
@chrisl8 

Now that we have Godot4.3 beta with feature freeze, it is time to implement this demo correctly

**Comment by GeorgeS2019** [comment]
https://github.com/godotengine/godot-proposals/discussions/9885#discussion-6775936

**Review by aaronfranke — APPROVED** [review]
Even though this is incomplete, I'm going to merge this anyway, and further PRs can port this more. Thanks for getting this started!

**Comment by GeorgeS2019** [comment]
@aaronfranke 

It needs to stress that this partial demo is not up to date with the latest 4.3 skeletonModifier.

there is now a project in c# using the latest skeleton3Dmodifier for IK

**Comment by chrisl8** [comment]
Thanks, and acknowledged that my work got the demo past some basic "won't even start in Godot 4" issues, but is far from a solution to the real problem.

Unfortunately my free time to work on this has evaporated. Glad I could help. I'll jump in again if I get time again, but for now I must leave what i was able to do here.

**Comment by GeorgeS2019** [comment]
@Calinou 

The demo is not complete and there is no check if it is consistent with the latest implementation of Animation concept introduced in Godot 4.3 and 4.4:


There needs to clearly state that this demo is not  working to avoid others wasting time on 3D IK for Godot4 

image

**Pull request merged**
