### PR TITLE
Change 3D Platformer Visuals

### PR DESCRIPTION
**Pull request by MangoDragonHub**
The following changes I made is updating the visuals for the 3D Platformer Demo for Godot 4.
I made a new Core Material and separate texture to update the original art direction that was in the original demo

Before (Godot 3)
Screenshot from 2022-10-02 21-21-09

After (Godot 4)
Screenshot from 2022-10-04 14-05-46
)

### CODE REVIEW

**Comment by aaronfranke** [comment]
Why is the player's body transparent?

Also, please don't title things as "update" when they are significantly changing things.

**Comment by adamscott** [comment]
@MangoDragonHub is a designer, not much a developer. I think this PR must be on the updated visual rather than the code itself.

**Comment by MangoDragonHub** [comment]
@aaronfranke I think the reason why the player looks transparent is because of how metallic and reflective the Player's material is. 
Also, when I upgraded the project from Godot 3 to 4, a lot of things broke.

**Comment by Calinou** [comment]
> I think the reason why the player looks transparent is because of how metallic and reflective the Player's material is.

No, the player's body is clearly invisible on the screenshot.

**Comment by MangoDragonHub** [comment]
Ah, you're talking about the body it self, not the material. Yeah, due to the Godot 3 to Godot 4 conversion tool not being ready, A LOT of stuff broke. Not just the scripting, all the character animations broke too. That's why the character and even the enemies in the background looks like that.

**Comment by jtnicholl** [comment]
Ignoring the fact that there are unresolved merge conflicts committed and it doesn't even run, I don't like these changes aesthetically.
The level geometry is still very blocky yet the textures are very detailed, it ends up looking like those [super-HD Minecraft texture packs](https://i.redd.it/2ioobk3vhgn21.jpg) or something. It's not very consistent. It also doesn't tile seamlessly.
I made a PR to update this demo and made changes to the visuals there as well (#770), and I went in the opposite direction. I adjusted the lighting to make the scene brighter, and I disabled texture filtering and set the texture compression to lossless to make it _more_ cleanly pixelated, and while it's just my opinion I think that looks a lot nicer. More HD detail is not always better.

**Comment by Calinou** [comment]
Superseded by https://github.com/godotengine/godot-demo-projects/pull/770 and https://github.com/godotengine/godot-demo-projects/pull/782. Thanks for the contribution nonetheless!

**Pull request closed without merging**
