### PR TITLE
Port demos with remade art assets to Godot 4

### PR DESCRIPTION
**Pull request by Calinou**
This re-ports the following demos to Godot 4 following their latest `3.x` versions:

- 2D Navigation with AStarGrid2D
- 2D JRPG Demo (todo)
- 2D Isometric Game
- 2D Platformer

Some tweaks have also been made in the process, such as split screen players having different colors in the 2D Platformer demo.

~~I'm having trouble porting the 2D JRPG demo due to AnimationTree stuff I'm not proficient with. Could someone lend a hand?~~
**Edit:** Fixed by https://github.com/Calinou/godot-demo-projects/pull/3. Thanks @Nonparoxysmic!

- This closes https://github.com/godotengine/godot-demo-projects/issues/879
and closes https://github.com/godotengine/godot-demo-projects/issues/785.

## Preview

navigation_astar webp

isometric webp

platformer webp

### CODE REVIEW

**Comment by jtnicholl** [comment]
The existing 4.0 version of the 2D platformer included cleaned up scripts, reorganized files, and improved controls. I'd prefer not to have that all be undone.

**Comment by Calinou** [comment]
> The existing 4.0 version of the 2D platformer included cleaned up scripts, reorganized files, and improved controls. I'd prefer not to have that all be undone.

Sorry, I don't see an easy way to merge both. Redoing all the tiles and animations from scratch would be too much work.

**Comment by moth-boi** [comment]
> I'm having trouble porting the 2D JRPG demo due to AnimationTree stuff I'm not proficient with. Could someone lend a hand?
@Calinou Do you still need help with that? Or is it finished?

**Comment by Calinou** [comment]
> @Calinou Do you still need help with that? Or is it finished?

I still need help with that, and won't have time to work on this in the near future. So please look into it if you can – it'll be very appreciated :slightly_smiling_face:

**Comment by Calinou** [comment]
This should be good to merge thanks to @Nonparoxysmic's work :slightly_smiling_face:

**Review by aaronfranke — APPROVED** [review]
Blind approval to unblock.

**Review by Geometror — COMMENTED** [review]
Did a quick test with all four demos. Almost all of them work fine, there's just one thing: The dialog box in the RPG demo looks a bit weird/broken.

image

**Comment by Calinou** [comment]
I've fixed the JRPG demo UI theme (and have also increased font sizes to match the rest of the UI):

image

image

However, there's an issue with the navigation demo I get since 4.1. Nothing happens when I click on empty space on the TileMap, and I get this error:

```
ERROR: Can't get id path. Point (0, 0) out of bounds [P: (1, 1), S: (16, 8)].
   at: get_point_path (core/math/a_star_grid_2d.cpp:492)
```

**Comment by smix8** [comment]
Tested the 4 demos:

- 2D Navigation with AStarGrid2D - works fine
- 2D JRPG Demo (todo) - works with 4.2 but does not work with Godot master due to TileMapLayer changes.
- 2D Isometric Game - works fine but has some weird "soft" shadow changes in the middle around where the carpet is placed.
- 2D Platformer - works fine

**Review by smix8 — APPROVED** [review]
Demos work for 4.2.1 if that is the current target.

**Pull request merged**
